name: rime
description: An SDK for pubnub chat applications
version: 0.1.0
author: "Perceive Software Solutions"
homepage: " "

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: 5.0.6
  flutter_bloc: ^6.1.2
  pubnub: ^3.1.0
  tuple: ^1.0.3
  flutter_easyrefresh: ^2.1.8
  flutter_slidable: ^0.5.7
  photo_manager: ^0.5.8
  colorful_safe_area: ^0.2.1
  dashed_container: ^1.0.1
  video_player: ^1.0.1
  extended_image: ^1.5.0
  pedantic: ^1.9.0
  giphy_client: ^0.2.0
  flutter_staggered_grid_view: ^0.3.4
  hive: ^1.4.4+1
  equatable: ^1.2.6
  intl: ^0.17.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  progress_dialog: 1.2.0
  permission_handler: ^4.0.0
  preload_page_view: ^0.1.4
  flutter_dotenv: ^3.1.0

flutter:

  uses-material-design: true

  assets:
    - .env

